import type {
  BookingDraft,
  Conversation,
  OpenRideWorkflowState,
  PassengerTrip,
  PublishDraft,
  PublishedTrip,
  Ride,
  UserProfile,
} from "./types";

export const defaultUserProfile: UserProfile = {
  ageLabel: "28 ans",
  bio: "Bonjour ! Je m'appelle Ronald, je fais régulièrement le trajet Paris-Lyon pour le travail. J'aime discuter de musique et de cinéma, mais j'apprécie aussi les trajets calmes. Au plaisir de voyager avec vous !",
  birthDate: "1995-08-15",
  city: "Paris",
  country: "France",
  currency: "EUR (€)",
  email: "ronald.richards@example.com",
  emergencyContactName: "Jane Doe",
  emergencyContactPhone: "+1 (555) 111-2222",
  firstName: "Ronald",
  fullName: "Ronald Richards",
  gender: "male",
  language: "French",
  lastName: "Richards",
  memberSince: "2023",
  miniRoleLabel: "Membre depuis 2023",
  phone: "+33 6 12 34 56 78",
  rating: 4.8,
  reviewCount: 124,
  tripCount: 45,
  verification: {
    emailVerified: true,
    idVerified: false,
    phoneVerified: true,
  },
};

export const ridesSeed: Ride[] = [
  {
    arrivalDateLabel: "Jeu 24 Oct",
    arrivalLocation: "Lyon",
    arrivalStation: "Gare Part-Dieu",
    arrivalTime: "12:30",
    carImage: "https://storage.googleapis.com/uxpilot-auth.appspot.com/add288faf4-4b04d15c38e772fef16c.png",
    dateLabel: "Jeudi, 24 Octobre 2023",
    departureDateLabel: "Jeu 24 Oct",
    departureLocation: "Paris",
    departureStation: "Porte Maillot (Metro Ligne 1)",
    departureTime: "08:00",
    distanceLabel: "0.5 km away",
    driver: {
      avatar: "https://storage.googleapis.com/uxpilot-auth.appspot.com/avatars/avatar-4.jpg",
      memberSince: "2019",
      name: "Marcus T.",
      rating: 4.9,
      reviewCount: 128,
      shortName: "Marcus T.",
      verifiedLabel: "Profil vérifié",
      vehicleColor: "White",
      vehicleName: "Tesla Model 3",
    },
    durationLabel: "4h 30m",
    id: "ride-paris-lyon",
    mapImage: "https://storage.googleapis.com/uxpilot-auth.appspot.com/75df874086-dabfd9157546c19857ca.png",
    originCity: "Paris",
    price: 35,
    priceLabel: "€35",
    preferences: {
      ambience: "Discussion et musique",
      instantBook: true,
      luggage: "Moyen (sac de voyage)",
      petsAllowed: false,
      smokingAllowed: false,
    },
    routeLabel: "Paris → Lyon",
    seatsLeft: 2,
    seatsTotal: 3,
    serviceFee: 3.5,
    taxes: 0.7,
  },
  {
    arrivalDateLabel: "Ven 24 Nov",
    arrivalLocation: "Toulouse",
    arrivalStation: "Toulouse Centre",
    arrivalTime: "14:00",
    carImage: "https://storage.googleapis.com/uxpilot-auth.appspot.com/add288faf4-4b04d15c38e772fef16c.png",
    dateLabel: "Vendredi, 24 Novembre 2023",
    departureDateLabel: "Ven 24 Nov",
    departureLocation: "Bordeaux",
    departureStation: "Bordeaux Saint-Jean",
    departureTime: "09:15",
    distanceLabel: "2.1 km away",
    driver: {
      avatar: "https://storage.googleapis.com/uxpilot-auth.appspot.com/avatars/avatar-5.jpg",
      memberSince: "2021",
      name: "Marie Laurent",
      rating: 4.7,
      reviewCount: 54,
      shortName: "Marie L.",
      verifiedLabel: "Profil vérifié",
      vehicleColor: "Blue",
      vehicleName: "Peugeot 3008",
    },
    durationLabel: "4h 45m",
    id: "ride-bordeaux-toulouse",
    mapImage: "https://storage.googleapis.com/uxpilot-auth.appspot.com/75df874086-dabfd9157546c19857ca.png",
    originCity: "Bordeaux",
    price: 32,
    priceLabel: "€32",
    preferences: {
      ambience: "Calme",
      instantBook: false,
      luggage: "Petit",
      petsAllowed: true,
      smokingAllowed: false,
    },
    routeLabel: "Bordeaux → Toulouse",
    seatsLeft: 1,
    seatsTotal: 4,
    serviceFee: 3.2,
    taxes: 0.64,
  },
  {
    arrivalDateLabel: "Sam 25 Nov",
    arrivalLocation: "Lyon",
    arrivalStation: "Saint-Exupéry Airport",
    arrivalTime: "15:00",
    carImage: "https://storage.googleapis.com/uxpilot-auth.appspot.com/add288faf4-4b04d15c38e772fef16c.png",
    dateLabel: "Samedi, 25 Novembre 2023",
    departureDateLabel: "Sam 25 Nov",
    departureLocation: "Paris",
    departureStation: "Orly Airport",
    departureTime: "10:30",
    distanceLabel: "12 km away",
    driver: {
      avatar: "https://storage.googleapis.com/uxpilot-auth.appspot.com/avatars/avatar-8.jpg",
      memberSince: "2020",
      name: "David K.",
      rating: 5,
      reviewCount: 90,
      shortName: "David K.",
      verifiedLabel: "Profil vérifié",
      vehicleColor: "Black",
      vehicleName: "Renault Clio",
    },
    durationLabel: "4h 30m",
    id: "ride-paris-lyon-alt",
    mapImage: "https://storage.googleapis.com/uxpilot-auth.appspot.com/75df874086-dabfd9157546c19857ca.png",
    originCity: "Paris",
    price: 38,
    priceLabel: "€38",
    preferences: {
      ambience: "Silencieux",
      instantBook: false,
      luggage: "Small",
      petsAllowed: false,
      smokingAllowed: false,
    },
    routeLabel: "Paris → Lyon",
    seatsLeft: 3,
    seatsTotal: 4,
    serviceFee: 3.8,
    taxes: 0.76,
  },
];

export const defaultBookingDraft = (rideId: string | null): BookingDraft => ({
  email: "devon.lane@example.com",
  firstName: "Devon",
  lastName: "Lane",
  message: "Bonjour Marcus, j'aurai un petit sac à dos avec moi...",
  paymentMethod: "card",
  phone: "+33 6 12 34 56 78",
  rideId,
  seatCount: 1,
});

export const defaultPublishDraft: PublishDraft = {
  date: "",
  departure: "Paris",
  destination: "Lyon",
  instructions: "",
  luggageAllowed: true,
  petsAllowed: false,
  price: 35,
  seats: 3,
  smokingAllowed: false,
  time: "",
  vehicleName: "Peugeot 3008",
};

export const passengerTripsSeed: PassengerTrip[] = [
  {
    departureLabel: "Demain, 08:00",
    driverAvatar: "https://storage.googleapis.com/uxpilot-auth.appspot.com/avatars/avatar-4.jpg",
    driverName: "Thomas D.",
    id: "booking-existing-confirmed",
    kind: "upcoming",
    passengersLabel: "1/3",
    paymentStatus: "paid",
    price: 35,
    rideId: "ride-paris-lyon",
    routeLabel: "Paris → Lyon",
    status: "confirmed",
    vehicleName: "Peugeot 3008",
  },
  {
    departureLabel: "Ven 24 Nov, 14:30",
    driverAvatar: "https://storage.googleapis.com/uxpilot-auth.appspot.com/avatars/avatar-5.jpg",
    driverName: "Marie L.",
    id: "booking-existing-pending",
    kind: "upcoming",
    passengersLabel: "2/4",
    paymentStatus: "authorized",
    price: 22.5,
    rideId: "ride-bordeaux-toulouse",
    routeLabel: "Bordeaux → Toulouse",
    status: "pending",
    vehicleName: "Renault Clio",
  },
];

export const publishedTripsSeed: PublishedTrip[] = [
  {
    departureLabel: "Lun 27 Nov, 07:45",
    id: "published-trip-1",
    kind: "upcoming",
    passengersLabel: "2 places restantes",
    price: 29,
    rideId: "published-lyon-paris",
    routeLabel: "Lyon → Paris",
    seatsAvailable: 2,
    status: "published",
    vehicleName: "Peugeot 3008",
  },
];

export const conversationsSeed: Conversation[] = [
  {
    id: "conversation-ride-paris-lyon",
    isOnline: true,
    lastMessage: "Parfait, on se retrouve devant la gare !",
    lastTimestamp: "10:42",
    participantAvatar: "https://storage.googleapis.com/uxpilot-auth.appspot.com/avatars/avatar-4.jpg",
    participantName: "Thomas Dubois",
    participantRoleLabel: "Passager",
    paymentStateLabel: "Payé en ligne",
    rideId: "ride-paris-lyon",
    routeLabel: "Paris → Lyon",
    statusLabel: "Confirmée",
    unread: false,
    messages: [
      {
        id: "message-1",
        sender: "them",
        text: "Bonjour Devon ! J'ai réservé une place pour le trajet Paris-Lyon de demain.",
        timestamp: "10:30",
      },
      {
        id: "message-2",
        sender: "them",
        text: "Est-ce qu'il serait possible de se retrouver devant la gare de Lyon plutôt qu'à Bercy ? J'ai une valise assez lourde.",
        timestamp: "10:31",
      },
      {
        id: "message-3",
        sender: "me",
        text: "Salut Thomas ! Oui pas de problème, la gare de Lyon m'arrange aussi finalement.",
        timestamp: "10:35",
      },
      {
        attachmentImage: "https://images.unsplash.com/photo-1524661135-423995f22d0b?ixlib=rb-4.0.3&auto=format&fit=crop&w=500&q=60",
        attachmentLabel: "Je serai garé exactement ici, devant le dépose-minute :",
        id: "message-4",
        sender: "me",
        text: "",
        timestamp: "10:38",
      },
      {
        id: "message-5",
        sender: "them",
        text: "Parfait, on se retrouve devant la gare ! À demain.",
        timestamp: "10:42",
      },
    ],
  },
  {
    id: "conversation-ride-bordeaux-toulouse",
    isOnline: false,
    lastMessage: "Est-ce que vous avez de la place pour un grand sac ?",
    lastTimestamp: "Hier",
    participantAvatar: "https://storage.googleapis.com/uxpilot-auth.appspot.com/avatars/avatar-5.jpg",
    participantName: "Marie Laurent",
    participantRoleLabel: "Conductrice",
    paymentStateLabel: "Autorisé",
    rideId: "ride-bordeaux-toulouse",
    routeLabel: "Bordeaux → Toulouse",
    statusLabel: "En attente",
    unread: true,
    messages: [
      {
        id: "message-6",
        sender: "them",
        text: "Est-ce que vous avez de la place pour un grand sac ?",
        timestamp: "Hier",
      },
    ],
  },
  {
    id: "conversation-ride-paris-lyon-alt",
    isOnline: false,
    lastMessage: "Merci pour le trajet, c'était super !",
    lastTimestamp: "Lun",
    participantAvatar: "https://storage.googleapis.com/uxpilot-auth.appspot.com/avatars/avatar-8.jpg",
    participantName: "Lucas Martin",
    participantRoleLabel: "Passager",
    paymentStateLabel: "Terminé",
    rideId: "ride-paris-lyon-alt",
    routeLabel: "Paris → Lyon",
    statusLabel: "Terminée",
    unread: false,
    messages: [
      {
        id: "message-7",
        sender: "them",
        text: "Merci pour le trajet, c'était super !",
        timestamp: "Lun",
      },
    ],
  },
];

export const openRideWorkflowStorageKey = "openride.workflow";

export function createInitialWorkflowState(): OpenRideWorkflowState {
  return {
    activeConversationId: conversationsSeed[0].id,
    authStatus: "anonymous",
    authVariant: null,
    bookingDraft: defaultBookingDraft(ridesSeed[0].id),
    conversations: conversationsSeed,
    onboardingStep: "complete",
    passengerTrips: passengerTripsSeed,
    profileCompleted: true,
    publishDraft: defaultPublishDraft,
    publishedTrips: publishedTripsSeed,
    rides: ridesSeed,
    selectedRideId: ridesSeed[0].id,
    trustCompleted: true,
    user: defaultUserProfile,
  };
}
